services:
  php:
    image: php:8.2-fpm
    build: .
    container_name: php
    volumes:
      - .:/var/www/html
      - ./Docker/php.ini:/usr/local/etc/php/php.ini
    environment:
      - SYMFONY_ENV=dev
    ports:
      - "9000:9000"
    depends_on:
      - mysql
  #mariadb:
  #  image: mariadb:latest
  #  container_name: mariadb
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_DATABASE: symfony
  #    MYSQL_USER: symfony
  #    MYSQL_PASSWORD: symfony
  #  ports:
  #    - "3307:3306" # Le port local est maintenant 3307
  #  volumes:
  #    - gl_db_data:/var/lib/mysql
  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grocerylist
      MYSQL_USER: grocerylist
      MYSQL_PASSWORD: grocerylist
    ports:
      - "3307:3306" # Le port local est maintenant 3307
    volumes:
      - gl_db_data:/var/lib/mysql
  mailer:
    image: axllent/mailpit:latest
    container_name: mailer
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MAILPIT_RELAY=127.0.0.1:25
      # MP_SMTP_AUTH_ACCEPT_ANY: 1
      # MP_SMTP_AUTH_ALLOW_INSECURE: 1
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./Docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql # Nom du conteneur MySQL
      PMA_PORT: 3306    # Port interne utilisé par phpMyAdmin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80" # Accès à phpMyAdmin via le port 8081
    depends_on:
      - mysql
volumes:
  gl_db_data: